import { PropertyType, Role, PropertyStatus } from '@prisma/client';

export const demoUsers = [
  {
    id: 'user-demo-landlord-1',
    name: 'João Silva (Locador SP)',
    phoneNumber: '+5511999990001',
    role: Role.LANDLORD,
    createdAt: new Date(),
  },
  {
    id: 'user-demo-tenant-1',
    name: 'Maria Souza (Locatária)',
    phoneNumber: '+5511999990002',
    role: Role.TENANT,
    createdAt: new Date(),
  }
];

export const demoProperties = [
  {
    id: 'prop-demo-sp-1',
    landlordId: 'user-demo-landlord-1',
    title: 'Apartamento Moderno na Paulista',
    description: 'Excelente apartamento com vista para a Avenida Paulista, recém reformado.',
    price: 4500.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Paulista, 1000',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    type: PropertyType.APARTMENT,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    area: 85.5,
    isFurnished: true,
    petsAllowed: false,
    latitude: -23.5614,
    longitude: -46.6559,
    nearSubway: true,
    isFeatured: true,
    views: 150,
    condoFee: 800.00,
    propertyTax: 250.00,
    createdAt: new Date(),
  },
  {
    id: 'prop-demo-rj-1',
    landlordId: 'user-demo-landlord-1',
    title: 'Casa Espaçosa no Leblon',
    description: 'Casa a duas quadras da praia, perfeita para família.',
    price: 12000.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Rua Dias Ferreira, 500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22431-050',
    type: PropertyType.HOUSE,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    area: 250.0,
    isFurnished: false,
    petsAllowed: true,
    latitude: -22.9841,
    longitude: -43.2234,
    nearSubway: true,
    isFeatured: true,
    views: 320,
    condoFee: 0.0,
    propertyTax: 600.00,
    createdAt: new Date(),
  }
];
