import { PropertyType, Role, PropertyStatus, ModerationStatus } from '@prisma/client';
import {
  DEMO_LANDLORD_1_ID,
  DEMO_TENANT_1_ID,
  DEMO_ADMIN_ID,
  DEMO_PROPERTY_SP_1_ID,
  DEMO_PROPERTY_RJ_1_ID,
  DEMO_PROPERTY_RJ_2_ID,
  DEMO_PROPERTY_RJ_3_ID,
  DEMO_PROPERTY_RJ_4_ID,
  DEMO_IMAGE_RJ_1_ID,
  DEMO_IMAGE_RJ_2_ID,
  DEMO_IMAGE_RJ_3_ID,
  DEMO_IMAGE_RJ_4_ID,
  DEMO_IMAGE_RJ2_1_ID,
  DEMO_IMAGE_RJ2_2_ID,
  DEMO_IMAGE_RJ2_3_ID,
  DEMO_IMAGE_RJ2_4_ID,
  DEMO_IMAGE_RJ3_1_ID,
  DEMO_IMAGE_RJ3_2_ID,
} from './demoIds';

export const demoUsers = [
  {
    id: DEMO_LANDLORD_1_ID,
    name: process.env.LANDLORD_NAME || 'João Silva (Locador SP)',
    email: process.env.LANDLORD_EMAIL || 'landlord@imoveis.com',
    phoneNumber: process.env.LANDLORD_PHONE_NUMBER || '+5511999990001',
    firebaseUid: process.env.LANDLORD_FIREBASE_UID || 'mock-landlord-firebase-uid',
    role: Role.LANDLORD,
    createdAt: new Date(),
  },
  {
    id: DEMO_TENANT_1_ID,
    name: 'Maria Souza (Locatária)',
    phoneNumber: '+5511999990002',
    role: Role.TENANT,
    createdAt: new Date(),
  },
  {
    id: DEMO_ADMIN_ID,
    name: process.env.ADMIN_NAME || 'Admin AlphaToca',
    email: process.env.ADMIN_EMAIL || 'admin@alphatoca.com',
    phoneNumber: process.env.ADMIN_PHONE_NUMBER || '+5511900000000',
    firebaseUid: process.env.ADMIN_FIREBASE_UID || 'mock-admin-firebase-uid',
    role: Role.ADMIN,
    createdAt: new Date(),
  }
];

export const demoProperties = [
  {
    id: DEMO_PROPERTY_SP_1_ID,
    landlordId: DEMO_LANDLORD_1_ID,
    title: 'Apartamento Moderno na Paulista',
    description: 'Excelente apartamento com vista para a Avenida Paulista, recém reformado.',
    price: 4500.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Paulista, 1000',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    type: PropertyType.APARTMENT,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    area: 85.5,
    isFurnished: true,
    petsAllowed: false,
    latitude: -23.5614,
    longitude: -46.6559,
    nearSubway: true,
    isFeatured: true,
    views: 150,
    condoFee: 800.00,
    propertyTax: 250.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: DEMO_PROPERTY_RJ_1_ID,
    landlordId: DEMO_LANDLORD_1_ID,
    title: 'Casa Espaçosa no Leblon',
    description: 'Casa a duas quadras da praia, perfeita para família.',
    price: 12000.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Rua Dias Ferreira, 500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22431-050',
    type: PropertyType.HOUSE,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    area: 250.0,
    isFurnished: false,
    petsAllowed: true,
    latitude: -22.9841,
    longitude: -43.2234,
    nearSubway: true,
    isFeatured: true,
    views: 320,
    condoFee: 0.0,
    propertyTax: 600.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: DEMO_PROPERTY_RJ_2_ID,
    landlordId: DEMO_LANDLORD_1_ID,
    title: 'Apartamento com Vista Mar em Copacabana',
    description: 'Lindo apartamento na orla de Copacabana, frente para o mar, reformado.',
    price: 6500.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Atlântica, 1500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22021-000',
    type: PropertyType.APARTMENT,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    area: 110.0,
    isFurnished: true,
    petsAllowed: true,
    latitude: -22.9673,
    longitude: -43.1788,
    nearSubway: true,
    isFeatured: true,
    views: 240,
    condoFee: 1200.00,
    propertyTax: 350.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: DEMO_PROPERTY_RJ_3_ID,
    landlordId: DEMO_LANDLORD_1_ID,
    title: 'Studio Moderno em Botafogo',
    description: 'Studio compacto e super bem localizado em Botafogo, ideal para solteiros ou casais.',
    price: 3200.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Rua Voluntários da Pátria, 300',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22270-010',
    type: PropertyType.STUDIO,
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    area: 45.0,
    isFurnished: true,
    petsAllowed: false,
    latitude: -22.9519,
    longitude: -43.1852,
    nearSubway: true,
    isFeatured: false,
    views: 110,
    condoFee: 500.00,
    propertyTax: 120.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: DEMO_PROPERTY_RJ_4_ID,
    landlordId: DEMO_LANDLORD_1_ID,
    title: 'Cobertura Duplex em Ipanema',
    description: 'Exclusiva cobertura em Ipanema com piscina privativa e vista deslumbrante.',
    price: 25000.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Vieira Souto, 800',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22420-002',
    type: PropertyType.APARTMENT,
    bedrooms: 4,
    bathrooms: 5,
    parkingSpots: 3,
    area: 320.0,
    isFurnished: false,
    petsAllowed: true,
    latitude: -22.9866,
    longitude: -43.2030,
    nearSubway: true,
    isFeatured: true,
    views: 450,
    condoFee: 3500.00,
    propertyTax: 1500.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  }
];

export const demoPropertyImages = [
  {
    id: DEMO_IMAGE_RJ_1_ID,
    propertyId: DEMO_PROPERTY_RJ_1_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_1_ID}/0001.png`,
    isCover: true,
    caption: 'Fachada Principal',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ_2_ID,
    propertyId: DEMO_PROPERTY_RJ_1_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_1_ID}/0002.png`,
    isCover: false,
    caption: 'Sala de Estar',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ_3_ID,
    propertyId: DEMO_PROPERTY_RJ_1_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_1_ID}/0003.png`,
    isCover: false,
    caption: 'Cozinha',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ_4_ID,
    propertyId: DEMO_PROPERTY_RJ_1_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_1_ID}/0004.png`,
    isCover: false,
    caption: 'Quarto',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ2_1_ID,
    propertyId: DEMO_PROPERTY_RJ_2_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_2_ID}/0001.png`,
    isCover: true,
    caption: 'Sala',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ2_2_ID,
    propertyId: DEMO_PROPERTY_RJ_2_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_2_ID}/0002.png`,
    isCover: false,
    caption: 'Quarto',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ2_3_ID,
    propertyId: DEMO_PROPERTY_RJ_2_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_2_ID}/0003.png`,
    isCover: false,
    caption: 'Banheiro',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ2_4_ID,
    propertyId: DEMO_PROPERTY_RJ_2_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_2_ID}/0004.png`,
    isCover: false,
    caption: 'Cozinha',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ3_1_ID,
    propertyId: DEMO_PROPERTY_RJ_3_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_3_ID}/0001.jpeg`,
    isCover: true,
    caption: 'Estudio',
    createdAt: new Date(),
  },
  {
    id: DEMO_IMAGE_RJ3_2_ID,
    propertyId: DEMO_PROPERTY_RJ_3_ID,
    url: `http://10.0.2.2:3000/uploads/${DEMO_PROPERTY_RJ_3_ID}/0002.jpeg`,
    isCover: false,
    caption: 'Estudio',
    createdAt: new Date(),
  },


];
