import { PropertyType, Role, PropertyStatus, ModerationStatus } from '@prisma/client';

export const demoUsers = [
  {
    id: 'user-demo-landlord-1',
    name: 'João Silva (Locador SP)',
    phoneNumber: '+5511999990001',
    role: Role.LANDLORD,
    createdAt: new Date(),
  },
  {
    id: 'user-demo-tenant-1',
    name: 'Maria Souza (Locatária)',
    phoneNumber: '+5511999990002',
    role: Role.TENANT,
    createdAt: new Date(),
  }
];

export const demoProperties = [
  {
    id: 'prop-demo-sp-1',
    landlordId: 'user-demo-landlord-1',
    title: 'Apartamento Moderno na Paulista',
    description: 'Excelente apartamento com vista para a Avenida Paulista, recém reformado.',
    price: 4500.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Paulista, 1000',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-100',
    type: PropertyType.APARTMENT,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    area: 85.5,
    isFurnished: true,
    petsAllowed: false,
    latitude: -23.5614,
    longitude: -46.6559,
    nearSubway: true,
    isFeatured: true,
    views: 150,
    condoFee: 800.00,
    propertyTax: 250.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: 'prop-demo-rj-1',
    landlordId: 'user-demo-landlord-1',
    title: 'Casa Espaçosa no Leblon',
    description: 'Casa a duas quadras da praia, perfeita para família.',
    price: 12000.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Rua Dias Ferreira, 500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22431-050',
    type: PropertyType.HOUSE,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    area: 250.0,
    isFurnished: false,
    petsAllowed: true,
    latitude: -22.9841,
    longitude: -43.2234,
    nearSubway: true,
    isFeatured: true,
    views: 320,
    condoFee: 0.0,
    propertyTax: 600.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: 'prop-demo-rj-2',
    landlordId: 'user-demo-landlord-1',
    title: 'Apartamento com Vista Mar em Copacabana',
    description: 'Lindo apartamento na orla de Copacabana, frente para o mar, reformado.',
    price: 6500.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Atlântica, 1500',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22021-000',
    type: PropertyType.APARTMENT,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 1,
    area: 110.0,
    isFurnished: true,
    petsAllowed: true,
    latitude: -22.9673,
    longitude: -43.1788,
    nearSubway: true,
    isFeatured: true,
    views: 240,
    condoFee: 1200.00,
    propertyTax: 350.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: 'prop-demo-rj-3',
    landlordId: 'user-demo-landlord-1',
    title: 'Studio Moderno em Botafogo',
    description: 'Studio compacto e super bem localizado em Botafogo, ideal para solteiros ou casais.',
    price: 3200.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Rua Voluntários da Pátria, 300',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22270-010',
    type: PropertyType.STUDIO,
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 0,
    area: 45.0,
    isFurnished: true,
    petsAllowed: false,
    latitude: -22.9519,
    longitude: -43.1852,
    nearSubway: true,
    isFeatured: false,
    views: 110,
    condoFee: 500.00,
    propertyTax: 120.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  },
  {
    id: 'prop-demo-rj-4',
    landlordId: 'user-demo-landlord-1',
    title: 'Cobertura Duplex em Ipanema',
    description: 'Exclusiva cobertura em Ipanema com piscina privativa e vista deslumbrante.',
    price: 25000.00,
    status: PropertyStatus.AVAILABLE,
    address: 'Avenida Vieira Souto, 800',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22420-002',
    type: PropertyType.APARTMENT,
    bedrooms: 4,
    bathrooms: 5,
    parkingSpots: 3,
    area: 320.0,
    isFurnished: false,
    petsAllowed: true,
    latitude: -22.9866,
    longitude: -43.2030,
    nearSubway: true,
    isFeatured: true,
    views: 450,
    condoFee: 3500.00,
    propertyTax: 1500.00,
    moderationStatus: ModerationStatus.APPROVED,
    createdAt: new Date(),
  }
];

export const demoPropertyImages = [
  {
    id: 'img-demo-rj-1',
    propertyId: 'prop-demo-rj-1',
    url: 'http://localhost:3000/uploads/prop-demo-rj-1/0001.png',
    isCover: true,
    caption: 'Fachada Principal',
    createdAt: new Date(),
  },
  {
    id: 'img-demo-rj-2',
    propertyId: 'prop-demo-rj-1',
    url: 'http://localhost:3000/uploads/prop-demo-rj-1/0002.png',
    isCover: false,
    caption: 'Sala de Estar',
    createdAt: new Date(),
  },
  {
    id: 'img-demo-rj-3',
    propertyId: 'prop-demo-rj-1',
    url: 'http://localhost:3000/uploads/prop-demo-rj-1/0003.png',
    isCover: false,
    caption: 'Cozinha',
    createdAt: new Date(),
  },
  {
    id: 'img-demo-rj-4',
    propertyId: 'prop-demo-rj-1',
    url: 'http://localhost:3000/uploads/prop-demo-rj-1/0004.png',
    isCover: false,
    caption: 'Quarto',
    createdAt: new Date(),
  }
];
