#!/usr/bin/env bash
#
# 04-cutover-env.sh — Swap the production .env from Supabase URLs to the local
# Postgres URL and restart the API via PM2.
#
# Target host: production server `desafio01.alphaedtech` (10.10.0.201).
#
# Run order: AFTER 03-restore-local.sh succeeds and the operator has confirmed
# row counts match Supabase. This is the moment the cutover becomes live.
#
# Inputs:
#   $1  Path to the production .env file (default: ./.env)
#   $2  New local Postgres password for role 'imoveis' (or read interactively).
#       The same value generated by 01-provision-postgres.sh.
#
# Env knobs:
#   PM2_NAME   — pm2 process name (default: alphatoca-backend).
#   APP_ROLE   — db role used in DATABASE_URL/DIRECT_URL (default: imoveis).
#   APP_DB     — db name (default: imoveis).
#   APP_HOST   — db host in URL (default: 127.0.0.1).
#   APP_PORT   — db port in URL (default: 5432).
#
# Source PRD: tasks/prd-supabase-to-localhost-db-migration.md (US-005, FR-3, FR-4).

set -euo pipefail

# --- Configurable knobs ---------------------------------------------------------
ENV_FILE="${1:-./.env}"
NEW_PASSWORD="${2:-}"
PM2_NAME="${PM2_NAME:-alphatoca-api}"
APP_ROLE="${APP_ROLE:-imoveis}"
APP_DB="${APP_DB:-imoveis}"
APP_HOST="${APP_HOST:-127.0.0.1}"
APP_PORT="${APP_PORT:-5432}"

BACKUP_FILE="${ENV_FILE}.pre-supabase-cutover.bak"

# --- Helpers --------------------------------------------------------------------
log()  { printf '[04-cutover] %s\n' "$*"; }
warn() { printf '[04-cutover][WARN] %s\n' "$*" >&2; }
fail() { printf '[04-cutover][FAIL] %s\n' "$*" >&2; exit 1; }

usage() {
    cat >&2 <<EOF_USAGE
Usage: $0 [path/to/.env] [new-local-password]

  \$1  Path to the production .env file (default: ./.env)
  \$2  New local Postgres password for role '${APP_ROLE}'.
       If omitted, the script prompts for it (read -s, hidden input).

Env overrides: PM2_NAME, APP_ROLE, APP_DB, APP_HOST, APP_PORT.

Backup: writes ${ENV_FILE}.pre-supabase-cutover.bak (refuses to overwrite).
EOF_USAGE
    exit 2
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
fi

# --- Pre-flight -----------------------------------------------------------------
if [[ ! -f "${ENV_FILE}" ]]; then
    fail "Env file not found at: ${ENV_FILE}"
fi
if ! command -v pm2 >/dev/null 2>&1; then
    fail "pm2 not found on PATH — install pm2 (npm i -g pm2) before running."
fi
if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 not found on PATH — required for URL-encoding the password."
fi

# Prompt for password if not provided. Use read -s so it doesn't echo to the terminal.
if [[ -z "${NEW_PASSWORD}" ]]; then
    if [[ ! -t 0 ]]; then
        fail "No password supplied as \$2 and stdin is not a tty — cannot prompt. Re-run with the password as the second arg."
    fi
    printf 'Enter the new local Postgres password for role %q: ' "${APP_ROLE}" >&2
    IFS= read -rs NEW_PASSWORD
    printf '\n' >&2
    if [[ -z "${NEW_PASSWORD}" ]]; then
        fail "Empty password — aborting."
    fi
fi

# --- Step 1 — backup ------------------------------------------------------------
log "Step 1/7 — backing up ${ENV_FILE} to ${BACKUP_FILE}…"
if [[ -e "${BACKUP_FILE}" ]]; then
    fail "Backup already exists at ${BACKUP_FILE}. Refusing to overwrite. Move/delete it manually if you really want to re-run."
fi
cp -p "${ENV_FILE}" "${BACKUP_FILE}"
log "  Backup written: ${BACKUP_FILE}"

# --- URL-encode password --------------------------------------------------------
ENCODED_PASSWORD="$(python3 -c 'import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=""))' "${NEW_PASSWORD}")"
NEW_DATABASE_URL="postgresql://${APP_ROLE}:${ENCODED_PASSWORD}@${APP_HOST}:${APP_PORT}/${APP_DB}?schema=public"
NEW_DIRECT_URL="${NEW_DATABASE_URL}"

# Use a delimiter that cannot appear in a URL-encoded password (no '|' produced by quote()).
SED_DELIM='|'

# --- Step 2 — substitute DATABASE_URL ------------------------------------------
log "Step 2/7 — rewriting DATABASE_URL to point at ${APP_HOST}:${APP_PORT}/${APP_DB}…"
if grep -qE '^[[:space:]]*DATABASE_URL=' "${ENV_FILE}"; then
    sed -i.tmp -E "s${SED_DELIM}^[[:space:]]*DATABASE_URL=.*\$${SED_DELIM}DATABASE_URL=${NEW_DATABASE_URL}${SED_DELIM}" "${ENV_FILE}"
    rm -f "${ENV_FILE}.tmp"
else
    warn "  No existing DATABASE_URL line — appending one."
    printf '\nDATABASE_URL=%s\n' "${NEW_DATABASE_URL}" >> "${ENV_FILE}"
fi

# --- Step 3 — substitute DIRECT_URL --------------------------------------------
log "Step 3/7 — rewriting DIRECT_URL to point at ${APP_HOST}:${APP_PORT}/${APP_DB}…"
if grep -qE '^[[:space:]]*DIRECT_URL=' "${ENV_FILE}"; then
    sed -i.tmp -E "s${SED_DELIM}^[[:space:]]*DIRECT_URL=.*\$${SED_DELIM}DIRECT_URL=${NEW_DIRECT_URL}${SED_DELIM}" "${ENV_FILE}"
    rm -f "${ENV_FILE}.tmp"
else
    log "  No existing DIRECT_URL line — appending one (Prisma uses it for migrations)."
    printf 'DIRECT_URL=%s\n' "${NEW_DIRECT_URL}" >> "${ENV_FILE}"
fi

# --- Step 4 — strip SUPABASE_ACCESS_TOKEN --------------------------------------
log "Step 4/7 — stripping any SUPABASE_ACCESS_TOKEN line…"
sed -i.tmp -E '/^[[:space:]]*SUPABASE_ACCESS_TOKEN=/d' "${ENV_FILE}"
rm -f "${ENV_FILE}.tmp"

# --- Step 5 — verify the env is clean ------------------------------------------
log "Step 5/7 — verifying ${ENV_FILE} contains no Supabase residue…"
LEFTOVERS=()
if grep -qF 'aws-1-us-west-2.pooler.supabase.com' "${ENV_FILE}"; then
    LEFTOVERS+=('aws-1-us-west-2.pooler.supabase.com')
fi
if grep -qF 'qkmseleljscluhhrcpaz' "${ENV_FILE}"; then
    LEFTOVERS+=('qkmseleljscluhhrcpaz')
fi
if grep -qE '^[[:space:]]*SUPABASE_ACCESS_TOKEN=' "${ENV_FILE}"; then
    LEFTOVERS+=('SUPABASE_ACCESS_TOKEN=')
fi

if [[ "${#LEFTOVERS[@]}" -gt 0 ]]; then
    warn "Residual Supabase references still present in ${ENV_FILE}:"
    for marker in "${LEFTOVERS[@]}"; do
        warn "  - ${marker}"
    done
    fail "Cutover .env still references Supabase — aborting BEFORE pm2 restart so you can fix manually. Backup is at ${BACKUP_FILE}."
fi
log "  No Supabase references remain. ${ENV_FILE} is clean."

# --- Step 6 — pm2 restart ------------------------------------------------------
log "Step 6/7 — restarting pm2 process '${PM2_NAME}' with --update-env…"
pm2 restart "${PM2_NAME}" --update-env

# --- Step 7 — tail recent logs -------------------------------------------------
log "Step 7/7 — tailing the last 50 log lines from '${PM2_NAME}' for inline review…"
pm2 logs "${PM2_NAME}" --lines 50 --nostream || warn "pm2 logs returned non-zero — check pm2 status manually."

# --- Final message -------------------------------------------------------------
cat <<EOF_DONE

Cutover complete for pm2 process '${PM2_NAME}'.
  Backup: ${BACKUP_FILE}
  New DATABASE_URL host: ${APP_HOST}:${APP_PORT}/${APP_DB}

Next: run scripts/db-migration/05-smoke-test.sh to validate health, Swagger,
and the live DB connection. If anything fails, the rollback runbook lives at
documentation/runbook-rollback-supabase.md.
EOF_DONE
